### ISSUE TITLE
ros-indigo-csm contains nothing

### ISSUE THREAD

**Issue by k-okada** [tork-a/csm-release#1]
```
$ dpkg -L ros-indigo-csm
/.
/opt
/opt/ros
/opt/ros/indigo
/opt/ros/indigo/share
/opt/ros/indigo/share/csm
/opt/ros/indigo/share/csm/package.xml
/usr
/usr/share
/usr/share/doc
/usr/share/doc/ros-indigo-csm
/usr/share/doc/ros-indigo-csm/changelog.Debian.gz
```

hope https://github.com/AndreaCensi/csm/pull/13 fixes

**Comment by k-okada** [comment]
hope... means I' not confident at all about this.

**Comment by k-okada** [comment]
aha, we're using https://github.com/AndreaCensi/csm/blob/csm_eigen/CMakeLists.txt for deb releaase ,that's does not include anything..

**Comment by 130s** [comment]
Done in https://github.com/AndreaCensi/csm/issues/9#issuecomment-154775514
