### ISSUE TITLE
Release for kinetic

### ISSUE THREAD

**Issue by stwirth** [tork-a/csm-release#3]
Hi,
could we get a release for kinetic please? Code seems to compile fine (with some warnings) on Ubuntu 16.04/kinetic.
Thanks!

**Comment by k-okada** [comment]
@stwirth ok, done -> https://github.com/ros/rosdistro/pull/14128

**Comment by stwirth** [comment]
Awesome, thanks!

**Comment by 130s** [comment]
@k-okada If you could share how to make a release of this package I can handle the release in the future.
I tried, but I'm not familiar with this specific type of 3rd party release setting.

(There seems to be a few newer commits since 1.0.2 was made back in 2015 btw https://github.com/AndreaCensi/csm/commits/master)

**Comment by k-okada** [comment]
I just ran `bloom-release --rosdistro kinetic --track kinetic`

--
◉ Kei Okada


2017-03-09 5:15 GMT+09:00 Isaac I.Y. Saito <notifications@github.com>:

**Comment by 130s** [comment]
Unfortunately csm keeps failing on ROS buildfarm so I requested to revert for now https://github.com/ros/rosdistro/pull/14154

[Someone](http://answers.ros.org/question/229488/csm-package-not-found/?answer=254342#post-id-254342) seems have been able to be able to build csm on Kinetic. If someone can try patching the [upstream repo](https://github.com/AndreaCensi/csm) that'll be great.

**Comment by k-okada** [comment]
fixed , see https://github.com/ros/rosdistro/pull/14156
From quick look, error on build firm (http://build.ros.org/job/Kbin_uX64__csm__ubuntu_xenial_amd64__binary/5/console) may not related post in answers.ros.org
we need https://github.com/tork-a/csm-release/commit/d4b2cd84b709c53d32c4aae9b6e1be8bbbcba163

**Comment by 130s** [comment]
Thank you for the immediate response. It seems [building](http://repositories.ros.org/status_page/ros_kinetic_default.html?q=csm) now!
