### ISSUE TITLE
Release into ROS melodic

### ISSUE THREAD

**Issue by patrickcjh** [tork-a/csm-release#4]
I would like to request the maintainer to release this package into the ROS melodic distro.

**Comment by k-okada** [comment]
thanks, relleased in both noetic and melodic  https://github.com/ros/rosdistro/pull/25222 https://github.com/ros/rosdistro/pull/25221

**Comment by patrickcjh** [comment]
Great. Thanks!

**Comment by patrickcjh** [comment]
Seems like the patch d4b2cd8 is required too, as the build is failing. http://build.ros.org/view/Mbin_uB64/job/Mbin_uB64__csm__ubuntu_bionic_amd64__binary/2/console

**Comment by k-okada** [comment]
thaks, should be fixed in http://github.com/ros/rosdistro/pull/25289 and https://github.com/ros/rosdistro/pull/25291

**Comment by patrickcjh** [comment]
Thanks again.
